### ISSUE TITLE
Scheduler doesn't work on windows 11 VM

### ISSUE THREAD

**Issue by jduust** [itk-dev-rpa/OpenOrchestrator#104]
```
Checking heartbeats...
Checking triggers...
Running trigger:  ExcelRefresherManual
Scheduler couldn't launch the process:
FileNotFoundError:
[WinError 2] Den angivne fil blev ikke fundet
Doing cleanup...
```
This is the only error message i get, there's no logs in the terminal either, so it seems it never proceeds to the venv/package installing. I don't have the same issues on my windows 10 or windows server machine. I figured it was due to having python 13, so i tried downgrading to python 12, but it's the same issue. This is the [process](https://github.com/mtm-aarhus/Python-ExcelRefresher), but i doubt it's related to the specific process.

**Comment by hbpe-aarhus** [comment]
Same error here with a fresh Python 3.12.7 install in a Windows 11 VM:

```
Checking heartbeats...
Checking triggers...
Running trigger:  MBA_Kørselskontoret_Skolelister_Single
Scheduler couldn't launch the process:
FileNotFoundError:
[WinError 2] Den angivne fil blev ikke fundet
Doing cleanup...
Waiting 6 seconds...
```

I have no issues running a Trigger in Scheduler on my laptop, which is also running Windows 11.

**Comment by hbpe-aarhus** [comment]
@jduust Pretty sure it's due to not having Git installed in the VM :) I installed it just now and the error went away.

https://git-scm.com/downloads/win

**Comment by jduust** [comment]
@hbpe-aarhus yep, already had git installed on previous machines so didn't even consider it, now it works
