### ISSUE TITLE
"File not found" message is spammed in console

### ISSUE THREAD

**Issue by hbpe-aarhus** [itk-dev-rpa/OpenOrchestrator#46]
Scheduler periodically prints "Den angivne fil blev ikke fundet." (File not found) when running.

Both Orchestrator and Scheduler can connect to the file-based SQLite database, though.

Execution of processes works as expected and status in the database is updated when triggers are run.

Steps to reproduce:

1) Initialize a new database using SQLite. For instance using the connection string "sqlite+pysqlite:///C:\\OpenOrchestratorDB\\test_database.db" on Windows.

2) Connect both Orchestrator and Scheduler to the database, using the same encryption key.

3) Scheduler periodically reports "Den angivne fil blev ikke fundet" even though it is connected to the database.

**Comment by ghbm-itk** [comment]
The message "Den angivne sti blev ikke fundet" has nothing to do with SQLite and it can be ignored.

It's because Scheduler tries to delete all inactive robots on the system, but if there aren't any it prints the message.

**Comment by hbpe-aarhus** [comment]
Well, in that case I don't think it should print the message if there are no inactive robots. It's pretty confusing to the user :)

**Comment by ghbm-itk** [comment]
Agreed. It will be removed in a coming update :)
