### ISSUE TITLE
Dropdown and/or default values for 'Date from' and 'Date to'

### ISSUE THREAD

**Issue by hbpe-aarhus** [itk-dev-rpa/OpenOrchestrator#51]
On the 'Logs' tab, the default values for 'Date from' and 'Date to' are currently 'dd-mm-yyyy hh:mm:ss'.

It would be nice to have the fields pre-populated (for instance with the last day) and/or a dropdown that lets you choose "Last Hour", "Last Day" etc.

Mostly a user experience improvement but obviously not a huge priority at this point :)

**Comment by ghbm-itk** [comment]
A complete overhaul is coming to the UI. This problem is also addressed there :)
