### ISSUE TITLE
Log level "Error" does not display error

### ISSUE THREAD

**Issue by hbpe-aarhus** [itk-dev-rpa/OpenOrchestrator#52]
When using the default Log level (empty string), errors are shown in the Logs pane, but when selecting "Error" as Log level, they are not shown.

See attached screenshots for an example.

![log_level_error](https://github.com/itk-dev-rpa/OpenOrchestrator/assets/58694666/c038652e-bb6d-411c-b41f-fba19edacfaa)
![log_level_empty](https://github.com/itk-dev-rpa/OpenOrchestrator/assets/58694666/9fb67da5-320a-4aca-9c2e-e8a12ecaa158)

**Comment by ghbm-itk** [comment]
I'm not able to reproduce this.. Do you get any errors in the console?

**Comment by hbpe-aarhus** [comment]
Yes, I am using SQLite and no errors are shown in the console.
